FaceCheckin/Models/DB/Course.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceCheckin.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Course
    {
        public Course()
        {
            this.STUDENT_COURSE = new HashSet<STUDENT_COURSE>();
        }

        [Required(ErrorMessage = "Mã lớp không được để trống!")]
        [RegularExpression("[A-Za-z0-9]*$", ErrorMessage = "Mã lớp không chứa ký tự đặc biệt, không sử dụng tiếng Việt!")]
        [Display(Name = "Mã lớp")]
        public string idCourse { get; set; }
        [Required(ErrorMessage = "Tên lớp không được để trống!")]
        [RegularExpression("[^.*?^${}()@#%$]*$", ErrorMessage = "Tên lớp không chứa ký tự đặc biệt")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Tên lớp phải từ 3 đến 50 ký tự.")]
        [Display(Name = "Tên lớp")]
        public string CourseName { get; set; }
        [Required(ErrorMessage = "Ngày bắt đầu không được để trống!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "Ngày kết thúc không được để trống!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }
        public string idInstructor { get; set; }
        [Required(ErrorMessage = "Năm học không được để trống!")]
        [Display(Name = "Năm học")]
        public string SchoolYear { get; set; }
        [Display(Name = "Thuộc bộ môn")]
        public string idDepartment { get; set; }
		public Nullable<int> NumberOfCourse { get; set; }

        public string I_Name { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<STUDENT_COURSE> STUDENT_COURSE { get; set; }
    }
}

FaceCheckin/Models/ViewModels/CourseViewModel.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FaceCheckin.Models.ViewModels
{
    public class CourseViewModel
    {
        public Course Course { get; set; }
        public IEnumerable<Instructor> Instructors { get; set; }
        public IEnumerable<Department> Departments { get; set; }
        public IEnumerable<Schedule> Schedules { get; set; }
    }
    public class CourseDetailsVM
    {
        public int CourseNo { get; set; }
        public Course Course { get; set; }
        public IEnumerable<DateTime> CourseDate { get; set; }
        public List<List<bool>> lstchk { get; set; }
        public List<List<string>> lstlate { get; set; }
        public int[] rowcntNAbs { get; set; }
        public int[] rowcntAbs { get; set; }
        public int[] clmncntNAbs { get; set; }
    }
    public class AddStdExcel
    {
        public string idStudent { get; set; }
        public string S_Name { get; set; }
        public string idCourse { get; set; }
        public string SchoolYear { get; set; }
        public int idSC { get; set; }
    }
    public class StdSum
    {
        public string idStudent { get; set; }
        public Course Course { get; set; }
        public string currentCourseNo { get; set; }
        public string S_Name { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<DateTime> S_Dob { get; set; }
        public int? NoAbsent { get; set; }
        public int? NoLate { get; set; }
        public int? NoCourse { get; set; }
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public IEnumerable<DateTime> CourseDate { get; set; }
        public List<string> tick { get; set; }
        public int? absWarning { get; set; }
        public int? lateWarning { get; set; }
    }
    public class DetailStdVM
    {
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CrsIndex { get; set; }
        public bool isAvailable { get; set; }
    }
    public class DocumentModelView
    {
        public HttpPostedFileBase ExcelFileName { get; set; }
    }
    public class AddStdVM
    {
        public bool Selected { get; set; }
        public string idStudent { get; set; }
        public string S_Name { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<DateTime> S_Dob { get; set; }
        public string ClassName { get; set; }
        public string idCourse { get; set; }
        public string SchoolYear { get; set; }
        public int NoLate { get; set; }
        public int NoAbsent { get; set; }
        public int idSC { get; set; }
    }
    public class StdAddListVM
    {
        public List<AddStdVM> StdList { get; set; }
    }
    public class AddCourseVM
    {
        public string Mon1 { get; set; }
        public string Tue1 { get; set; }
        public string Wed1 { get; set; }
        public string Thu1 { get; set; }
        public string Fri1 { get; set; }
        public string Sat1 { get; set; }
        public string Sun1 { get; set; }
        public string Mon2 { get; set; }
        public string Tue2 { get; set; }
        public string Wed2 { get; set; }
        public string Thu2 { get; set; }
        public string Fri2 { get; set; }
        public string Sat2 { get; set; }
        public string Sun2 { get; set; }
        public bool chk1 { get; set; }
        public bool chk2 { get; set; }
        public bool chk3 { get; set; }
        public bool chk4 { get; set; }
        public bool chk5 { get; set; }
        public bool chk6 { get; set; }
        public bool chk7 { get; set; }
        public string idDepartment { get; set; }
        public string DepartmentName { get; set; }
        public Course Course { get; set; }
        public IEnumerable<Instructor> Instructors { get; set; }
        public IEnumerable<Department> Departments { get; set; }
        public IEnumerable<Schedule> Schedules { get; set; }
    }
}

FaceCheckin/Controllers/CourseController.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using System.Linq.Dynamic;
using FaceCheckin.Models.ViewModels;
using FaceCheckin.Security;
using System.Web.Script.Serialization;
using System.Data.OleDb;
using System.Data;
using System.Xml;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Text;
using LinqToExcel;
using System.Data.Entity.Validation;

namespace FaceCheckin.Controllers
{
    [CustomAuthorize(Roles = "Admin,Trưởng khoa,Phó khoa,Trưởng bộ môn,Phó bộ môn,Giảng viên,Trợ giảng")]
    public class CourseController : Controller
    {
        private FCI_DBEntities db = new FCI_DBEntities();
        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult Index()
        {
            var facu = CustomFacu();
            ViewBag.FacuList = facu;
            var schy = db.Courses.ToList().GroupBy(test => test.SchoolYear).Select(grp => grp.First());
            ViewBag.SchList = schy;
            return View();
        }

        private List<Faculty> CustomFacu()
        {
            var facu = db.Faculties.ToList();
            if (!User.IsInRole("Admin"))
            {
                string tmp = Session["idIns"].ToString();
                facu = (from f in db.Faculties
                        join d in db.Departments on f.idFaculty equals d.idFaculty
                        join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                        where i.idInstructor == tmp
                        select f).ToList();
            }
            return facu;
        }

        [HttpPost]
        public ActionResult getDeptList(string id)
        {
            var lstdept = (from e in db.Departments
                           where e.idFaculty == id.ToString()
                           select new
                           {
                               e.idDepartment,
                               e.DepartmentName
                           }).ToList();
            if (!User.IsInRole("Admin") && !User.IsInRole("Trưởng khoa") && !User.IsInRole("Phó khoa"))
            {
                string tmp = Session["idIns"].ToString();
                var idf = getIdDept(tmp);
                lstdept = (from e in db.Departments
                           where e.idFaculty == id.ToString() && e.idDepartment == idf.ToString()
                           select new
                           {
                               e.idDepartment,
                               e.DepartmentName
                           }).ToList();
            }

            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstdept);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult getInsList(string id)
        {
            var lstins = (from e in db.Instructors
                          where e.I_idDepartment == id.ToString()
                          select new
                          {
                              e.idInstructor,
                              e.I_Name
                          }).ToList();
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstins);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult getCourses()
        {
            db.Configuration.LazyLoadingEnabled = false;
            var Draw = Request.Form.GetValues("draw").FirstOrDefault();
            var Start = Request.Form.GetValues("start").FirstOrDefault();
            var Length = Request.Form.GetValues("length").FirstOrDefault();

            var SortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][data]").FirstOrDefault();
            var SortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var idCourse = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            var CourseName = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
            var InstructorName = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
            var DepartmentName = Request.Form.GetValues("columns[6][search][value]").FirstOrDefault();
            var SchoolYear = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault();

            int PageSize = Length != null ? Convert.ToInt32(Length) : 0;
            int Skip = Start != null ? Convert.ToInt32(Start) : 0;
            int TotalRecords = 0;
            var course = (from e in db.Courses
                          join ab in db.Instructors on e.idInstructor equals ab.idInstructor into a
                          from ab in a.DefaultIfEmpty()
                          join f in db.Departments on e.idDepartment equals f.idDepartment
                          join i in db.Instructors on ab.idInstructor equals i.idInstructor into ic
                          from i in ic.DefaultIfEmpty()
                          select new
                          {
                              idCourse = e.idCourse,
                              CourseName = e.CourseName,
                              StartDate = e.StartDate,
                              EndDate = e.EndDate,
                              DepartmentName = f.DepartmentName,
                              SchoolYear = e.SchoolYear,
                              InstructorName = ab == null ? "(Chưa có GV)" : ab.I_Name
                          }).ToList();
            if (User.IsInRole("Giảng viên") || User.IsInRole("Trợ giảng"))
            {
                string tmp = Session["idIns"].ToString();
                course = (from e in db.Courses
                          join ab in db.Instructors on e.idInstructor equals ab.idInstructor into a
                          from ab in a.DefaultIfEmpty()
                          join f in db.Departments on e.idDepartment equals f.idDepartment
                          join i in db.Instructors on ab.idInstructor equals i.idInstructor into ic
                          from i in ic.DefaultIfEmpty()
                          where e.idInstructor == tmp
                          select new
                          {
                              idCourse = e.idCourse,
                              CourseName = e.CourseName,
                              StartDate = e.StartDate,
                              EndDate = e.EndDate,
                              DepartmentName = f.DepartmentName,
                              SchoolYear = e.SchoolYear,
                              InstructorName = ab == null ? "(Chưa có GV)" : ab.I_Name
                          }).ToList();
            }
            //SEARCHING...
            if (!string.IsNullOrEmpty(idCourse))
            {
                course = course.Where(a => a.idCourse.Contains(idCourse)).ToList();
            }
            if (!string.IsNullOrEmpty(CourseName))
            {
                course = course.Where(a => a.CourseName.Contains(CourseName)).ToList();
            }
            if (!string.IsNullOrEmpty(DepartmentName))
            {
                course = course.Where(a => a.DepartmentName.ToString() == DepartmentName.ToString()).ToList();
            }
            if (!string.IsNullOrEmpty(InstructorName))
            {
                course = course.Where(a => a.InstructorName.Contains(InstructorName)).ToList();
            }
            if (!string.IsNullOrEmpty(SchoolYear))
            {
                course = course.Where(a => a.SchoolYear == SchoolYear).ToList();
            }
            if (!(string.IsNullOrEmpty(SortColumn) && string.IsNullOrEmpty(SortColumnDir)))
            {
                course = course.OrderBy(SortColumn + " " + SortColumnDir).ToList();
            }


            TotalRecords = course.ToList().Count();
            var NewItems = course.Skip(Skip).Take(PageSize == -1 ? TotalRecords : PageSize).ToList();

            return Json(new { draw = Draw, recordsFiltered = TotalRecords, recordsTotal = TotalRecords, data = NewItems }, JsonRequestBehavior.AllowGet);
        }
        private AddCourseVM CustomDept()
        {
            var dept = db.Departments.ToList();
            if (!User.IsInRole("Admin"))
            {
                string tmp = Session["idIns"].ToString();
                var idf = getIdDept(tmp);
                dept = (from d in db.Departments
                        join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                        where i.idInstructor == tmp
                        select d).ToList();
                if (!User.IsInRole("Trưởng khoa") && !User.IsInRole("Phó khoa"))
                {
                    dept = (from e in db.Departments
                            where e.idDepartment == idf.ToString()
                            select e).ToList();
                }
            }
            var viewModel = new AddCourseVM
            {
                Departments = dept
            };
            return viewModel;
        }
        [CustomAuthorize(Roles = "Admin,Trưởng khoa,Trưởng bộ môn")]
        public ActionResult Create(string parameterID)
        {
            var facu = db.Departments.Single(c => c.idDepartment == parameterID).DepartmentName;
            var viewModel = new AddCourseVM
            {
                idDepartment = parameterID,
                DepartmentName = facu
            };
            return PartialView("_CreateCourse", viewModel);
        }
        [CustomAuthorize(Roles = "Admin,Trưởng khoa,Trưởng bộ môn")]
        [HttpPost]

FaceCheckin/Views/Course/Details.cshtml
@model FaceCheckin.Models.ViewModels.CourseDetailsVM

@{
    ViewBag.Header = "Danh sách Học sinh thuộc Lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="MyModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="MyModalContent"></div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div>
    <div>
        <dl class="dl-horizontal" style="margin-bottom:10px">
            <dt style="text-align: left; width: 130px">
                <label>Mã lớp tín chỉ: </label>
            </dt>
            <dd style="margin-left:0px">
                <p> @Html.DisplayFor(model => model.Course.idCourse)</p>
            </dd>
            <dt style="text-align: left; width: 130px">
                <label>Tên lớp tín chỉ: </label>
            </dt>
            <dd style="margin-left:0px">
                <p> @Html.DisplayFor(model => model.Course.CourseName, new { @id = "idstd" })</p>
            </dd>
        </dl>
        <div style="margin-bottom:15px;text-align:left;margin-right:15px">
            <div>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary">Thêm sinh viên vào lớp</button>
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Thêm từng sinh viên", "AddStudentToCourse", null, new { id = Model.Course.idCourse }, new { data_modal = "" })</li>
                        <li>@Html.ActionLink("Thêm danh sách", "AddListStudentToCourse", null, new { id = Model.Course.idCourse }, new { data_modal = "" })</li>
                        <li class="divider"></li>
                        <li>@Html.ActionLink("Nhập bằng Excel", "AddListStudentToCourseFromExcel", null, new { data_modal = "" })</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div>
        <div class="ck-button col-lg-10" style="margin-bottom:10px">
            <label><input type="checkbox" value="1" name="detailsinformation" checked="checked" style="margin-top: 10px"><span>&nbsp;&nbsp;Hiển thị chi tiết</span></label>
        </div>
        <div style="margin-bottom:10px;text-align:right;margin-right:15px">
            <button id="btn-export" title="Xuất ra Excel" class="btn btn-primary" style="text-align:right"><i class="fa fa-file-excel-o"></i>&nbsp;&nbsp;Xuất ra Excel</button>
        </div>
    </div>
    @*<div style="text-align:right" class="col-lg-6">
        </div>*@
    <div>
        <div class="divScoll" id="dvscr" style="overflow-x: auto; overflow-y: visible;margin-left:430px">
            <table class="table table-striped" id="tblsum" style="margin-top:0px; table-layout:fixed; background-color: #FFF">
                <tr>
                    <td style="position:absolute;left:10px;width:40px;">
                        <strong>STT</strong>
                    </td>
                    <td style="position:absolute;left:50px;width:100px;">
                        <strong>Mã Sinh viên</strong>
                    </td>
                    <td style="position:absolute;left:150px;width:200px;">
                        <strong>Tên Sinh viên</strong>
                    </td>
                    <td style="position:absolute;left:350px;width:90px;">
                        <strong>Ngày sinh</strong>
                    </td>
                    @foreach (var item in Model.CourseDate)
                    {
                        <td class="detailsinformation" style="width:80px; column-rule-color:white"><strong>@item.ToString("dd/MM/yyyy")</strong></td>
                    }

                    <td style="width:250px;font-weight:bold; text-align:center">
                        <strong>Số buổi vắng/ <small>Tổng số buổi</small></strong>
                    </td>
                    <td style="width:250px;font-weight:bold;text-align:center">
                        <strong>Số buổi đi trễ</strong>
                    </td>
                </tr>

                @foreach (var item in Model.Course.STUDENT_COURSE.Select((item, index) => new { item, index }))
                {
                    <tr>
                        <td style="position:absolute;left:10px;width:40px">
                            @(item.index + 1)
                        </td>
                        <td style="position: absolute; left: 0; width: 100px; margin-left: 50px; ">
                            @Html.DisplayFor(modelItem => item.item.idStudent)
                        </td>
                        <td style="position: absolute; left: 0; width: 200px; margin-left: 150px; ">
                            @Html.ActionLink(item.item.Student.S_Name, "DetailsReport", "Course", new { idStudent = item.item.idStudent, idCourse = Model.Course.idCourse }, null)
                        </td>
                        <td style="position: absolute; left: 0; width: 90px; margin-left: 350px">
                            @Html.DisplayFor(modelItem => item.item.Student.S_Dob)
                        </td>
                        @foreach (var j in item.item.chksch)
                        {
                            if (j == "false")
                            {
                                <th class="detailsinformation danger">Vắng</th>
                            }
                            else if (j == "true")
                            {
                                <th class="detailsinformation success">Đi học</th>
                            }
                            else if (j == null)
                            {
                                <th class="detailsinformation"></th>
                            }
                            else
                            {
                                <th class="detailsinformation info">Đi trễ @j phút</th>
                            }

                        }
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.item.NoAbsent)/@Html.DisplayFor(modelItem => Model.CourseNo)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(modelItem => item.item.NoLate)
                        </td>
                    </tr>
                }
                <tr>
                    <td colspan="4" style="position: absolute; left: 0; width: 440px;text-align:center" class="detailsinformation"><strong>Đi học</strong></td>
                    @for (int rc = 0; rc < Model.rowcntNAbs.Length; rc++)
                    {
                        <td class="detailsinformation">@Model.rowcntNAbs[rc]</td>
                    }
                </tr>
                <tr>
                    <td colspan="4" style="position: absolute; left: 0; width: 440px;text-align:center" class="detailsinformation"><strong>Vắng</strong></td>
                    @for (int rc = 0; rc < Model.rowcntAbs.Length; rc++)
                    {
                        <td class="detailsinformation">@Model.rowcntAbs[rc]</td>
                    }
                </tr>

            </table>

        </div>
    </div>
</div>
@*@foreach (var tt in Model.lstlate)
    {
        @tt
    }*@
<p>
    <button class="buttonPrevious btn btn-primary" style="margin-top: 20px" onclick="goBack()">Trở về</button>
    @*@Html.ActionLink("Trở về", "Index", null, new { @class = "buttonPrevious btn btn-primary" })*@
</p>
<script src="~/Scripts/jquery.table2excel.js"></script>
<script>
    $("input:checkbox:not(:checked)").each(function () {
        var column = "table ." + $(this).attr("name");
        $(column).hide();
    });

    $("input:checkbox").click(function () {
        var column = "table ." + $(this).attr("name");
        $(column).toggle();
    });
    $('#btn-export').on('click', function () {
        //$('#tblsum').find("tr td a").replaceWith(function () {
        //    return $.text([this]);
        //});
        $('<table>').append($('#tblsum tr').clone()).table2excel({
            exclude: ".noExl",
            fileext: ".xls",
            name: "Worksheet Name",
            exclude_links: false,
            filename: "@Model.Course.idCourse - @Model.Course.CourseName" //do not include extension
        });
    });
    function goBack() {
        window.history.back();
    }
</script>
<style>
    /*tr td {
        background-color: #FFF;
    }*/
    tr:nth-child(odd) > td,
    tr:nth-child(odd) > th {
        background-color: #f9f9f9;
    }
    /*tr, td {
        border: 1px solid #ddd !important;
    }*/
</style>

FaceCheckin/Views/Course/_CreateListStudent.cshtml
@model FaceCheckin.Models.ViewModels.AddStdVM
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="MyModalTitle">Thêm mới sinh viên vào lớp</h4>
</div>
<style>
    .modal .modal-dialog {
        width: 60%;
    }

    ul.ui-front {
        z-index: 1100;
    }

    .ui-autocomplete {
        background-color: inherit;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateListStd" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-list-ol"></i></span>
                <input type="text" name="search" id="id_search" placeholder="Tìm theo lớp sinh hoạt" class="form-control" style="width:85%" autofocus />
                <button type="button" class="btn btn-flat" id="btnsearch" onclick="getCrsStatistic()">Tìm kiếm&nbsp;<i class="fa fa-search"></i></button>
            </div>
            <br />
            <div id="sumcontent">
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <input type="submit" class="btn btn-primary" value="Thêm mới" id="btnSubmit" />
    </div>
}
<link rel="stylesheet" href="~/Content/jquery-ui.css">
<script src="~/Scripts/moment/min/moment.min.js"></script>
<script src="~/Scripts/jQueryUI/jquery-ui.js"></script>
<script src="~/Scripts/jquery.quicksearch.js"></script>
<script>
    $(document).ready(function () {
        getclass();
        $.validator.unobtrusive.parse('#CreateListStd');
        $("#btnSubmit").click(function () {
            if (!$("#CreateListStd").valid()) {
                return false;
            }
            location.reload();
        });
        function getclass() {
            var repeatingEvents
            $.ajax
            ({
                url: '/Course/getClassList',
                type: 'POST',
                datatype: 'application/json',
                contentType: 'application/json',
                success: function (result) {
                    var projects = [];
                    $.each($.parseJSON(result), function (i, dept) {
                        var b = {
                            value: dept.ClassName,
                            label: dept.idClass
                        }
                        projects.push(b);
                    })
                    $("#id_search").autocomplete({
                        minLength: 0,
                        source: projects,
                        focus: function (event, ui) {
                            $("#id_search").val(ui.item.label);
                            return false;
                        },
                        select: function (event, ui) {
                            $("#id_search").html(ui.item.label);
                            return false;
                        }
                    })
                .autocomplete("instance")._renderItem = function (ul, item) {
                    return $("<li>")
                      .append("<div>" + item.value + "<br>" + item.label + "</div>")
                      .appendTo(ul);
                };
                },
                error: function () {
                    alert("Whooaaa! Something went wrong..")
                },
            });
        }
    });
    function getCrsStatistic() {
        var aid = $("#id_search").val();
        var bid = "@Model.idCourse";
        var cid = "@Model.SchoolYear";
        var url = '@Url.Action("PartialSta", "Course", new { parameterID = "-1", idc="-2", sch="-3"})';
        url = url.replace("-1", aid);
        url = url.replace("-2", bid);
        url = url.replace("-3", cid);
        url = url.replace(/&amp;/g, "&");
        $("#sumcontent").load(url)
    }
</script>