FaceCheckin/Models/ViewModels/ClassesViewModel.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FaceCheckin.Models.ViewModels
{
    public class ClassesViewModel
    {
    }
    public partial class FacultyView
    {
        public string idFaculty { get; set; }
        public string FacultyName { get; set; }
    }
    public partial class DepartmentViewModels
    {
        public string idDepartment { get; set; }
        public string DepartmentName { get; set; }
        public string idFaculty { get; set; }
    }
    public class StdSumVM
    {
        public Student Student { get; set; }
        public List<OneCrs> Courses { get; set; }
    }
    public class OneCrs
    {
        public string idCourse { get; set; }
        public string CourseName { get; set; }
        public string AbsSum { get; set; }
        public string  LateSum { get; set; }
        public string SchoolYear { get; set; }
    }
    public class ClassesVM
    {
        public Class Class { get; set; }
        public IEnumerable<Instructor> Instructors { get; set; }
        public IEnumerable<Department> Departments { get; set; }
    }
}

FaceCheckin/Controllers/ClassesController.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq.Dynamic;
using FaceCheckin.Models.ViewModels;
using FaceCheckin.Security;
using System.Web.Script.Serialization;
using LinqToExcel;
using System.Data.OleDb;
using System.Data;
using System.Data.Entity.Validation;

namespace FaceCheckin.Controllers
{
    [CustomAuthorize(Roles = "Admin,Trưởng khoa,Phó khoa,Trưởng bộ môn,Phó bộ môn,Giảng viên,Trợ giảng")]
    public class ClassesController : Controller
    {
        private FCI_DBEntities db = new FCI_DBEntities();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult Index()
        {
            var facu = CustomFacu();
            ViewBag.FacuList = facu;
            var schy = db.Classes.ToList().GroupBy(test => test.SchoolYear).Select(grp => grp.First());
            ViewBag.SchList = schy;
            return View();
        }
        public ActionResult Summary(string id)
        {
            //Session["idstd"] = id;
            var schy = db.Courses.ToList().GroupBy(test => test.SchoolYear).Select(grp => grp.First());
            ViewBag.SchList = schy;
            var std = db.Students.Single(c => c.idStudent == id);
            return View(std);
        }
        [HttpPost]
        public ActionResult getSum(string id)
        {
            db.Configuration.LazyLoadingEnabled = false;
            var Draw = Request.Form.GetValues("draw").FirstOrDefault();
            var Start = Request.Form.GetValues("start").FirstOrDefault();
            var Length = Request.Form.GetValues("length").FirstOrDefault();

            var SortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][data]").FirstOrDefault();
            var SortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var idCourse = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            var SchoolYear = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();
            //var idStudent = Url.RequestContext.RouteData.Values["id"].ToString();

            int PageSize = Length != null ? Convert.ToInt32(Length) : 0;
            int Skip = Start != null ? Convert.ToInt32(Start) : 0;
            int TotalRecords = 0;
            //var ids=TempData["idstd"].ToString();
            var crs = (from c in db.Courses
                       join st in db.STUDENT_COURSE on c.idCourse equals st.idCourse
                       where st.idStudent == id
                       select new
                       {
                           idCourse = c.idCourse,
                           CourseName = c.CourseName,
                           SchoolYear = c.SchoolYear,
                           AbsSum = st.NoAbsent + "/" + c.NumberOfCourse,
                           LateSum = st.NoLate + "/" + (c.NumberOfCourse - st.NoAbsent)
                       }).ToList();
            if (!string.IsNullOrEmpty(idCourse))
            {
                crs = crs.Where(a => a.idCourse.Contains(idCourse)).ToList();
            }
            if (!string.IsNullOrEmpty(SchoolYear))
            {
                crs = crs.Where(a => a.SchoolYear == SchoolYear).ToList();
            }
            if (!(string.IsNullOrEmpty(SortColumn) && string.IsNullOrEmpty(SortColumnDir)))
            {
                crs = crs.OrderBy(SortColumn + " " + SortColumnDir).ToList();
            }
            TotalRecords = crs.ToList().Count();
            var NewItems = crs.Skip(Skip).Take(PageSize == -1 ? TotalRecords : PageSize).ToList();

            return Json(new { draw = Draw, recordsFiltered = TotalRecords, recordsTotal = TotalRecords, data = NewItems }, JsonRequestBehavior.AllowGet);
        }
        private List<Faculty> CustomFacu()
        {
            var facu = db.Faculties.ToList();
            if (!User.IsInRole("Admin"))
            {
                string tmp = Session["idIns"].ToString();
                facu = (from f in db.Faculties
                        join d in db.Departments on f.idFaculty equals d.idFaculty
                        join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                        where i.idInstructor == tmp
                        select f).ToList();
            }
            return facu;
        }

        [HttpPost]
        public ActionResult getDeptList(string id)
        {
            var lstdept = (from e in db.Departments
                           where e.idFaculty == id.ToString()
                           select new
                           {
                               e.idDepartment,
                               e.DepartmentName
                           }).ToList();
            if (!User.IsInRole("Admin") && !User.IsInRole("Trưởng khoa") && !User.IsInRole("Phó khoa"))
            {
                string tmp = Session["idIns"].ToString();
                var idf = getIdDept(tmp);
                lstdept = (from e in db.Departments
                           where e.idFaculty == id.ToString() && e.idDepartment == idf.ToString()
                           select new
                           {
                               e.idDepartment,
                               e.DepartmentName
                           }).ToList();
            }

            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstdept);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult getInsList(string id)
        {
            var lstins = (from e in db.Instructors
                          where e.I_idDepartment == id.ToString()
                          select new
                          {
                              e.idInstructor,
                              e.I_Name
                          }).ToList();
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstins);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult getClasses()
        {
            db.Configuration.LazyLoadingEnabled = false;
            var Draw = Request.Form.GetValues("draw").FirstOrDefault();
            var Start = Request.Form.GetValues("start").FirstOrDefault();
            var Length = Request.Form.GetValues("length").FirstOrDefault();

            var SortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][data]").FirstOrDefault();
            var SortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var idClass = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            var ClassName = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
            var InstructorName = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
            var DepartmentName = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault();
            var SchoolYear = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();

            int PageSize = Length != null ? Convert.ToInt32(Length) : 0;
            int Skip = Start != null ? Convert.ToInt32(Start) : 0;
            int TotalRecords = 0;
            var classes = (from e in db.Classes
                           join ab in db.Instructors on e.idInstructor equals ab.idInstructor into a
                           from ab in a.DefaultIfEmpty()
                           join f in db.Departments on e.idDepartment equals f.idDepartment
                           join i in db.Instructors on ab.idInstructor equals i.idInstructor into ic
                           from i in ic.DefaultIfEmpty()
                           select new
                           {
                               idClass = e.idClass,
                               ClassName = e.ClassName,
                               DepartmentName = f.DepartmentName,
                               SchoolYear = e.SchoolYear,
                               InstructorName = ab == null ? "(Chưa có GV cố vấn)" : ab.I_Name
                           }).ToList();
            if (User.IsInRole("Giảng viên") || User.IsInRole("Trợ giảng"))
            {
                string tmp = Session["idIns"].ToString();
                classes = (from e in db.Classes
                           join ab in db.Instructors on e.idInstructor equals ab.idInstructor into a
                           from ab in a.DefaultIfEmpty()
                           join f in db.Departments on e.idDepartment equals f.idDepartment
                           join i in db.Instructors on ab.idInstructor equals i.idInstructor into ic
                           from i in ic.DefaultIfEmpty()
                           where e.idInstructor == tmp
                           select new
                           {
                               idClass = e.idClass,
                               ClassName = e.ClassName,
                               DepartmentName = f.DepartmentName,
                               SchoolYear = e.SchoolYear,
                               InstructorName = ab.I_Name
                           }).ToList();
            }
            //SEARCHING...
            if (!string.IsNullOrEmpty(idClass))
            {
                classes = classes.Where(a => a.idClass.Contains(idClass)).ToList();
            }
            if (!string.IsNullOrEmpty(ClassName))
            {

FaceCheckin/Views/Classes/Details.cshtml
@model FaceCheckin.Models.DB.Class

@{
    ViewBag.Header = "Danh sách Học sinh thuộc Lớp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    /*Buttons to Right Side*/
    div.dt-buttons {
        float: right;
        position: relative;
        margin-left: 10px;
    }
    /*Table Info to right*/
    div.dataTables_wrapper div.dataTables_info {
        float: left;
        padding-top: 8px;
        white-space: nowrap;
    }
</style>
<div id="MyModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="MyModalContent"></div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<dl class="dl-horizontal" style="margin-bottom:10px">
    <dt style="text-align: left; width: 130px">
        <label>Mã lớp sinh hoạt: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(model => model.idClass)</p>
    </dd>
    <dt style="text-align: left; width: 130px">
        <label>Tên lớp sinh hoạt: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(model => model.ClassName, new { @id = "idstd" })</p>
    </dd>
</dl>
<p style="margin-bottom:5px">
    <div class="btn-group">
        <button type="button" class="btn btn-primary">Thêm sinh viên vào lớp</button>
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><a id="btncr" href="#">Thêm từng sinh viên</a></li>
            <li>@Html.ActionLink("Nhập bằng Excel", "AddListStudentToClassFromExcel", null, new { data_modal = "" })</li>
        </ul>
    </div>
</p>
<div>
    <table id="tblStudent" style="width:100%" class="table table-striped table-hover table-bordered table-responsive">
        <thead>
            <tr>
                <th>STT</th>
                <th>Mã sinh viên</th>
                <th>Tên sinh viên</th>
                <th>Ngày sinh</th>
                <th>Email</th>
                <th>Điện thoại</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th id="tht">Mã Sinh viên</th>
                <th id="tht">Tên Sinh viên</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>
<p>
    <button class="buttonPrevious btn btn-primary" style="margin-top: 20px" onclick="goBack()">Trở về</button>
</p>
<script>
    var table;
    $(document).ready(function () {
        $('#tblStudent tfoot #tht').each(function () {
            var title = $(this).text();
            $(this).html('<input class="FClass form-control" style="width:inherit;" type="text" id="' + title.replace(' ', '_') + '" placeholder="Tìm kiếm theo ' + title + '" />');
        });
        table = $('#tblStudent').DataTable({
            "ordering": true,
            "lengthMenu": [[25, 50, -1], [25, 50, "Tất cả"]],
            "pagingType": "full_numbers",
            "dom": 'Blrtip', // Hides Default Search
            "processing": true,
            "serverSide": true,
            "orderMulti": false,

            "ajax": {
                "url": "/Classes/getDetails",
                "type": "POST",
                "datatype": "json",
                "data": {
                    id: "@Model.idClass"
                }
            },
            "language": {
                "lengthMenu": "Hiển thị _MENU_ bản ghi trong một trang",
                "emptyTable": "Chưa có dữ liệu",
                "info": "Trang thứ _PAGE_ trong tổng số _PAGES_ trang",
                "infoEmpty": "Trống",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Trước",
                    "previous": "Sau"
                },
            },
            buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i>',
                            titleAttr: 'Copy'
                        },
                        {
                            extend: 'excelHtml5',
                            text: '<i class="fa fa-file-excel-o"></i>',
                            titleAttr: 'Excel',
                            title: 'Danh sách sinh viên thuộc lớp',
                            customize: function (xlsx) {
                                var sheet = xlsx.xl.worksheets['sheet1.xml'];
                                $('row c[r*="3"]', sheet).attr('s', '25');
                            }
                        },
                        {
                            extend: 'csvHtml5',
                            text: '<i class="fa fa-file-text-o"></i>',
                            titleAttr: 'CSV',
                            title: 'Danh sách sinh viên thuộc lớp'
                        },
                        {
                            extend: 'pdfHtml5',
                            text: '<i class="fa fa-file-pdf-o"></i>',
                            titleAttr: 'PDF',
                            title: 'Danh sách sinh viên thuộc lớp'
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa-print"></i>',
                            titleAttr: 'PRINT',
                            title: 'Danh sách sinh viên thuộc lớp'
                        }
            ],
            "fnDrawCallback": function (oSettings) {
                var count = $("#tblStudent").dataTable().fnSettings().aoData.length;
                if (count != 0) {
                    $(this).find('tbody tr').each(function (index) {
                        $(this).find('td').first(0).text(index + 1);
                    });
                }
            },
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [0] }
            ],
            "aaSorting": [[1, 'asc']],
            "aoColumns": [
                 {
                     "data": null, "autoWidth": true,
                     "sWidth": "30px"
                 },
                {
                    "data": "idStudent", "autoWidth": false,
                    "sWidth": "200px"
                },
               {
                   "data": "S_Name", "autoWidth": false, "mRender": function (data, type, full) {
                       var id = '"' + full['idStudent'] + '"';
                       var name = full['S_Name'];
                       return '<a href=' +
                          '@Url.Action("Summary", "Classes")/' + full['idStudent'] +
                          '>' + name + '</a>';
                   }
               },
                  {
                      "data": "S_Dob", "autoWidth": false,
                      "render": function (data, type, full) {
                          var data1 = data.replace("/Date(", "").replace(")/", "");
                          var date = new Date(parseInt(data1));
                          var month = date.getMonth() + 1;
                          return (date.getDate().toString().length > 1 ? date.getDate() : "0" + date.getDate()) + "/" + (month.toString().length > 1 ? month : "0" + month) + "/" + date.getFullYear();
                      },
                      "sWidth": "100px"
                  },
                  {
                      "data": "S_Email", "autoWidth": false,
                      "sWidth": "120px"
                  },
                  {
                      "data": "S_Phone", "autoWidth": false,
                      "sWidth": "120px"
                  }
            ]
        });
        table.columns().every(function () {
            var that = this;
            $('input', this.footer()).on('keyup change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });
    });
    function goBack() {
        window.history.back();
    }
    $("#btncr").click(function () {
        var productId = '@Model.idClass';
        var url = '@Url.Action("CreateNewStudent", "Classes", new { parameterID = "-1" })';
        url = url.replace("-1", productId);
        $("#MyModalContent").load(url, function () {
            $("#MyModal").modal({
                keyboard: false
            }, 'show');
            bindForm(this);
        });
        return false;
    });
</script>

FaceCheckin/Views/Classes/Summary.cshtml
@model FaceCheckin.Models.DB.Student
@{
    ViewBag.Title = "Thống kê chuyên cần";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<center><img src="~/Content/Images/underConstruction.png"></center>*@
<style>
    /*Buttons to Right Side*/
    div.dt-buttons {
        float: right;
        position: relative;
        margin-left: 10px;
    }
    /*Table Info to right*/
    div.dataTables_wrapper div.dataTables_info {
        float: left;
        padding-top: 8px;
        white-space: nowrap;
    }
</style>
<dl class="dl-horizontal">
    <dt style="text-align: left; width: 130px">
        <label>Họ tên sinh viên: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(model => model.S_Name)</p>
    </dd>
    <dt style="text-align: left; width: 130px">
        <label>Mã số sinh viên: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(model => model.idStudent, new { @id = "idstd" })</p>
    </dd>
    <dt style="text-align: left; width: 130px">
        <label>Ngày sinh: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(model => model.S_Dob)</p>
    </dd>
    <dt style="text-align: left; width: 130px">
        <label>Số điện thoại: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(modelItem => modelItem.S_Phone)</p>
    </dd>
    <dt style="text-align: left; width: 130px">
        <label> Email: </label>
    </dt>
    <dd style="margin-left:0px">
        <p> @Html.DisplayFor(modelItem => modelItem.S_Email)</p>
    </dd>
</dl>
Danh sách các lớp tín chỉ đang học:
<div class="form-group">
    <label class="control-label">Năm học</label>
    <select id="ddSch" class="form-control" style="width:30%">
        @foreach (var item in ViewBag.SchList)
        {
            <text>
                <option value="@item.SchoolYear">@item.SchoolYear</option>
            </text>
        }

    </select>
</div>
<div>
    <table id="tblSummary" style="width:100%" class="table table-striped table-hover table-bordered table-responsive">
        <thead>
            <tr>
                <th>STT</th>
                <th>Mã lớp tín chỉ</th>
                <th>Tên lớp tín chỉ</th>
                <th>Số buổi vắng/ Tổng số buổi</th>
                <th>Số buổi đi trễ/Tổng số buổi có mặt</th>
            </tr>
        </thead>
    </table>
</div>
<p>
    <button class="buttonPrevious btn btn-primary" style="margin-top: 20px" onclick="goBack()">Trở về</button>
</p>
<script>
    var table;
    $(document).ready(function () {
        table = $('#tblSummary').DataTable({
            "ordering": true,
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Tất cả"]],
            "pagingType": "full_numbers",
            "dom": 'Blrtip', // Hides Default Search
            "processing": true,
            "serverSide": true,
            "orderMulti": false,

            "ajax": {
                "url": "/Classes/getSum",
                "type": "POST",
                "datatype": "json",
                "data": {
                    id: "@Model.idStudent"
                }
            },
            "language": {
                "lengthMenu": "Hiển thị _MENU_ bản ghi trong một trang",
                "emptyTable": "Chưa có dữ liệu",
                "info": "Trang thứ _PAGE_ trong tổng số _PAGES_ trang",
                "infoEmpty": "Trống",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Trước",
                    "previous": "Sau"
                },
            },
            buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i>',
                            titleAttr: 'Copy'
                        },
                        {
                            extend: 'excelHtml5',
                            text: '<i class="fa fa-file-excel-o"></i>',
                            titleAttr: 'Excel',
                            title: 'Thống kê chuyên cần',
                            message: 'Thống kê chuyên cần',
                            customize: function (xlsx) {
                                var sheet = xlsx.xl.worksheets['sheet1.xml'];
                                $('row c[r*="3"]', sheet).attr('s', '25');
                            }
                        },
                        {
                            extend: 'csvHtml5',
                            text: '<i class="fa fa-file-text-o"></i>',
                            titleAttr: 'CSV',
                            title:'Thống kê chuyên cần',
                            message: 'Thống kê chuyên cần'
                        },
                        {
                            extend: 'pdfHtml5',
                            text: '<i class="fa fa-file-pdf-o"></i>',
                            titleAttr: 'PDF',
                            title: 'Thống kê chuyên cần',
                            message: 'Thống kê chuyên cần'
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa-print"></i>',
                            titleAttr: 'PRINT',
                            title: 'Thống kê chuyên cần',
                            message: 'Thống kê chuyên cần'
                        }
            ],
            "fnDrawCallback": function (oSettings) {
                var count = $("#tblSummary").dataTable().fnSettings().aoData.length;
                if (count != 0) {
                    $(this).find('tbody tr').each(function (index) {
                        $(this).find('td').first(0).text(index + 1);
                    });
                }
            },
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [0] }
            ],
            "aaSorting": [[1, 'asc']],
            "aoColumns": [
                 {
                     "data": null, "autoWidth": true,
                     "sWidth": "30px"
                 },
                {
                    "data": "idCourse", "autoWidth": false,
                    "sWidth": "200px"
                },
                {
                    "data": "CourseName", "autoWidth": false, "mRender": function (data, type, full) {
                        var id = '"' + full['idCourse'] + '"';
                        var name = full['CourseName'];
                        return '<a href=' +
                           '@Url.Action("DetailsReport", "Course")?idStudent=' + "@Model.idStudent" + "&idCourse=" + full['idCourse'] +
                           '>' + name + '</a>';
                    }
                },
                  {
                      "data": "AbsSum", "autoWidth": false,
                      "sWidth": "100px"
                  },
                  {
                      "data": "LateSum", "autoWidth": false,
                      "sWidth": "120px"
                  },
                  {
                      "data": "SchoolYear",
                      "visible": false
                  }
            ]
        });
        table.columns(5).search($('#ddSch').find('option:selected').text());
        //hit search on server
        table.draw();
    });
    $('#ddSch').change(function () {
        table.columns(5).search($('#ddSch').find('option:selected').text());
        //hit search on server
        table.draw();
    });
    function goBack() {
        window.history.back();
    }
</script>

FaceCheckin/Views/Classes/_CreateStudent.cshtml
@model FaceCheckin.Models.DB.Student
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="MyModalTitle">Thêm mới Sinh viên</h4>
</div>
<style>
    .modal .modal-dialog {
        width: 40%;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateStudent" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">

        <div class="form-horizontal">
            <div class="form-group cus">
                <label class="control-label">Thuộc lớp</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-list-ul"></i></span>
                   @Html.TextBoxFor(m => m.ClassName, new { @class = "form-control", @id = "clss",@readonly=true/*, @Value = @TempData["item1"]*/ })
                </div>
                @Html.ValidationMessageFor(m => m.ClassName, "", new { @class = "text-danger" })

            </div>
            @Html.HiddenFor(m=>m.idClass)
            <div class="form-group cus">
                <label class="control-label">Mã sinh viên</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-list-ol"></i></span>
                    @Html.TextBoxFor(m => m.idStudent, new { @class = "form-control", @placeholder = "Mã sinh viên" })
                </div>
                @Html.ValidationMessageFor(m => m.idStudent, "", new { @class = "text-danger" })

            </div>

            <div class="form-group cus">
                <label class="control-label">Tên sinh viên</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-align-center"></i></span>
                    @Html.TextBoxFor(m => m.S_Name, new { @class = "form-control", @placeholder = "Tên sinh viên" })
                </div>
                @Html.ValidationMessageFor(m => m.S_Name, "", new { @class = "text-danger" })

            </div>
            <div class="form-group cus">
                <label class="control-label">Ngày sinh</label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(m => m.S_Dob, new { @class = "form-control", style = "width:100%", type = "date" })
                </div>
                @Html.ValidationMessageFor(m => m.S_Dob, "", new { @class = "text-danger" })

            </div>
            <div class="form-group cus">
                @Html.LabelFor(m => m.S_Email, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                    @Html.TextBoxFor(m => m.S_Email, new { @class = "form-control", @placeholder = "Email" })
                </div>
                @Html.ValidationMessageFor(m => m.S_Email, "", new { @class = "text-danger" })

            </div>
            <div class="form-group cus">
                @Html.LabelFor(m => m.S_Phone, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                    @Html.TextBoxFor(m => m.S_Phone, new { @class = "form-control", @placeholder = "Số điện thoại" })
                </div>
                @Html.ValidationMessageFor(m => m.S_Phone, "", new { @class = "text-danger" })

            </div>

        </div>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <input type="submit" class="btn btn-primary" value="Thêm mới" id="btnSubmit" />
    </div>
}

<script>
    $(document).ready(function () {
        //getDeptList();
        $.validator.unobtrusive.parse('#CreateStudent');
        $("#btnSubmit").click(function () {
            if (!$("#CreateStudent").valid()) {
                return false;
            }
        });
    });
</script>