FaceCheckin/Models/DB/Department.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceCheckin.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Department
    {
        public Department()
        {
            this.Classes = new HashSet<Class>();
            this.Courses = new HashSet<Course>();
            this.Instructors = new HashSet<Instructor>();
        }

        [Required(ErrorMessage = "Mã bộ môn không được để trống!")]
        [Display(Name = "Mã bộ môn")]
        [RegularExpression("[A-Za-z]*$", ErrorMessage = "Mã bộ môn không chứa số, ký tự đặc biệt, không sử dụng tiếng việt!")]
        public string idDepartment { get; set; }
        [Required(ErrorMessage = "Tên bộ môn không được để trống!")]
        [RegularExpression("[^.*+?!^${}()@#%=$0-9]*$", ErrorMessage = "Tên bộ môn không chứa ký tự số và ký tự đặc biệt")]

        [StringLength(50, MinimumLength = 3, ErrorMessage = "Tên bộ môn phải từ 3 đến 50 ký tự.")]
        //[MinLength(2, ErrorMessage = "Tên bộ môn phải từ 2 đến 50 ký tự.")]
        [Display(Name = "Tên bộ môn")]
        public string DepartmentName { get; set; }
        [Required(ErrorMessage = "Tên khoa được để trống!")]
        [Display(Name = "Thuộc khoa")]
        public string idFaculty { get; set; }
        public string FacultyName { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}

FaceCheckin/Models/ViewModels/DepartmentViewModels.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FaceCheckin.Models.ViewModels
{
    public class DepartmentViewModel
    {
    }
    public class FacultyViewModels
    {
        public string idFaculty { get; set; }
         [Required]
        public string FacultyName { get; set; }
    }
    public class DeptVM
    {
        public Department Department { get; set; }
        public IEnumerable<Faculty> Faculties { get; set; }
    }
}

FaceCheckin/Controllers/DepartmentController.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq.Dynamic;
using FaceCheckin.Models.ViewModels;
using FaceCheckin.Security;

namespace FaceCheckin.Controllers
{
    [CustomAuthorize(Roles = "Admin,Trưởng khoa,Phó khoa")]
    public class DepartmentController : Controller
    {
        private FCI_DBEntities db = new FCI_DBEntities();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult Index()
        {
            var viewModel = CustomFacu();
            return View(viewModel);
        }
        private DeptVM CustomFacu()
        {
            var facu = db.Faculties.ToList();
            if (!User.IsInRole("Admin"))
            {
                string tmp = Session["idIns"].ToString();
                facu = (from f in db.Faculties
                        join d in db.Departments on f.idFaculty equals d.idFaculty
                        join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                        where i.idInstructor == tmp
                        select f).ToList();
            }
            var viewModel = new DeptVM
            {
                Faculties = facu
            };
            return viewModel;
        }
        [HttpPost]
        public ActionResult getDepartments()
        {
            db.Configuration.LazyLoadingEnabled = false;
            var Draw = Request.Form.GetValues("draw").FirstOrDefault();
            var Start = Request.Form.GetValues("start").FirstOrDefault();
            var Length = Request.Form.GetValues("length").FirstOrDefault();

            var SortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][data]").FirstOrDefault();
            var SortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var idDepartment = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            var DepartmentName = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
            var FacultyName = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();

            int PageSize = Length != null ? Convert.ToInt32(Length) : 0;
            int Skip = Start != null ? Convert.ToInt32(Start) : 0;
            int TotalRecords = 0;
            var dept = (from e in db.Departments
                        join f in db.Faculties on e.idFaculty equals f.idFaculty
                        select new
                        {
                            idDepartment = e.idDepartment,
                            DepartmentName = e.DepartmentName,
                            FacultyName = f.FacultyName
                        }).ToList();
            //SEARCHING...
            if (!string.IsNullOrEmpty(idDepartment))
            {
                dept = dept.Where(a => a.idDepartment.Contains(idDepartment)).ToList();
            }
            if (!string.IsNullOrEmpty(DepartmentName))
            {
                dept = dept.Where(a => a.DepartmentName.Contains(DepartmentName)).ToList();
            }
            if (!string.IsNullOrEmpty(FacultyName))
            {
                dept = dept.Where(a => a.FacultyName.ToString()==FacultyName.ToString()).ToList();
            }

            if (!(string.IsNullOrEmpty(SortColumn) && string.IsNullOrEmpty(SortColumnDir)))
            {
                dept = dept.OrderBy(SortColumn + " " + SortColumnDir).ToList();
            }

            TotalRecords = dept.ToList().Count();
            var NewItems = dept.Skip(Skip).Take(PageSize == -1 ? TotalRecords : PageSize).ToList();

            return Json(new { draw = Draw, recordsFiltered = TotalRecords, recordsTotal = TotalRecords, data = NewItems }, JsonRequestBehavior.AllowGet);
        }
        [CustomAuthorize(Roles = "Admin,Trưởng khoa")]
        public ActionResult Create(string parameterID)
        {
            var facu = db.Faculties.Single(c => c.idFaculty == parameterID).FacultyName;
            var viewModel = new Department
            {
                idFaculty = parameterID,
                FacultyName = facu
            };
            return PartialView("_CreateDepartment",viewModel);
        }
        [CustomAuthorize(Roles = "Admin,Trưởng khoa")]
        [HttpPost]
        public ActionResult Create(Department dept)
        {
            try
            {
                var facu = db.Faculties.ToList();
                dept.Faculties = facu;
                bool departmentExists = db.Departments.Any(fa => fa.idDepartment.Equals(dept.idDepartment));

                if (departmentExists)
                {
                    return new JsonResult
                    {
                        Data = new { ErrorMessage = "Đã tồn tại Bộ môn", Success = false },
                        ContentEncoding = System.Text.Encoding.UTF8,
                        JsonRequestBehavior = JsonRequestBehavior.DenyGet
                    };
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        db.Departments.Add(dept);
                        db.SaveChanges();
                        return Json(new { success = true, message = "Thêm mới thành công!" });
                    }
                    return PartialView("_CreateDepartment", dept);
                }
            }
            catch (Exception ex)
            {
                return new JsonResult
                {
                    Data = new { ErrorMessage = ex.Message, Success = false },
                    ContentEncoding = System.Text.Encoding.UTF8,
                    JsonRequestBehavior = JsonRequestBehavior.DenyGet
                };

            }
        }

        public ActionResult Edit(string id)
        {
            try
            {
                if (id == "")
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Department dept = db.Departments.Find(id);
                if (dept == null)
                    return HttpNotFound();
                var facu = db.Faculties.ToList();
                if (!User.IsInRole("Admin"))
                {
                    string tmp = Session["idIns"].ToString();
                    facu = (from f in db.Faculties
                            join d in db.Departments on f.idFaculty equals d.idFaculty
                            join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                            where i.idInstructor == tmp
                            select f).ToList();
                }
                DeptVM viewModel = new DeptVM()
                {
                    Faculties = facu,
                    Department = dept
                };
                return PartialView("_EditDepartment", viewModel);
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        public ActionResult getDeptDetails(string id)
        {
            try
            {
                var rslt = (from e in db.Departments
                            join f in db.Faculties on e.idFaculty equals f.idFaculty
                            where e.idDepartment == id.ToString()
                            select new
                            {
                                DepartmentName = e.DepartmentName,
                                FacultyName = f.FacultyName
                            });
                return Json(rslt, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        public ActionResult deleteConfirmed(string id)
        {
            try
            {
                var rslt = db.Departments.FirstOrDefault(x => x.idDepartment == id.ToString());
                if (rslt != null)
                {
                    db.Departments.Remove(rslt);
                    db.SaveChanges();
                    return Json("Xóa thành công!", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                return null;
            }
        }


        [HttpPost]
        public ActionResult Edit(DeptVM dept)
        {
            try
            {
                dept.Faculties = db.Faculties.ToList();
                if (ModelState.IsValid)
                {
                    db.Entry(dept.Department).State = EntityState.Modified;
                    db.SaveChanges();

                    return Json(new { success = true, message = "Cập nhật thành công!" });
                }
                return PartialView("_EditDepartment", dept);
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        [HttpPost]
        public ActionResult getDetails(string id)
        {
            db.Configuration.LazyLoadingEnabled = false;
            var Draw = Request.Form.GetValues("draw").FirstOrDefault();
            var Start = Request.Form.GetValues("start").FirstOrDefault();
            var Length = Request.Form.GetValues("length").FirstOrDefault();

            var SortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][data]").FirstOrDefault();
            var SortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var idClass = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();

FaceCheckin/Views/Department/Index.cshtml
@model FaceCheckin.Models.ViewModels.DeptVM

@{
    ViewBag.Title = "Quản lý Bộ môn";
    ViewBag.Header = "Danh sách Bộ môn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="MyModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="MyModalContent"></div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Department.idFaculty, htmlAttributes: new { @class = "control-label" })
    @Html.DropDownListFor(m => m.Department.idFaculty, new SelectList(Model.Faculties, "idFaculty", "FacultyName"),
                            htmlAttributes: new { @class = "form-control", @id = "ddlFacu", style = "width:30%" })
    @Html.ValidationMessageFor(m => m.Department.idFaculty, "", new { @class = "text-danger" })
</div>
@if (User.IsInRole("Admin") || User.IsInRole("Trưởng khoa"))
{
    @*<p>
        @Html.ActionLink("Thêm mới Bộ môn", "Create", null, null, new { data_modal = "", id = "btnCreate", @class = "btn btn-primary" })
    </p>*@
    <p>
        <button id="btncr" title="Thêm mới Bộ môn" class="btn btn-primary" style="text-align:right">&nbsp;&nbsp;Thêm mới Bộ môn</button>
    </p>
}
<input type="hidden" id="facu-id" />
<div>
    <table id="tblDepartments" style="width:100%" class="table table-striped table-hover table-bordered table-responsive">
        <thead>
            <tr>
                <th>STT</th>
                <th>Mã bộ môn</th>
                <th>Tên bộ môn</th>
                <th>Thuộc khoa</th>
                <th></th>
                <th></th>
                @*<th>Chi tiết</th>*@
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th id="tht">Mã bộ môn</th>
                <th id="tht">Tên bộ môn</th>
                <th></th>
                <th></th>
                <th></th>
                @*<th></th>*@
            </tr>
        </tfoot>
    </table>
</div>
<style>
    /*Buttons to Right Side*/
    div.dt-buttons {
        float: right;
        position: relative;
        margin-left: 10px;
    }
    /*Table Info to right*/
    div.dataTables_wrapper div.dataTables_info {
        float: left;
        padding-top: 8px;
        white-space: nowrap;
    }
</style>
<script>
    var table;
    var RoleCheck = @(User.IsInRole("Admin")? "true" : "false")
    $(document).ready(function () {
        document.onreadystatechange = function () {
            var idcls = $('#ddlFacu').find('option:selected').val()
            $("#facu-id").val(idcls);
            table.columns(3).search($('#ddlFacu').find('option:selected').text());
            //hit search on server
            table.draw();
        };
        $('#tblDepartments tfoot #tht').each(function () {
            var title = $(this).text();
            $(this).html('<input class="FClass form-control" style="width:inherit;" type="text" id="' + title.replace(' ', '_') + '" placeholder="Tìm kiếm theo ' + title + '" />');
        });
        table = $('#tblDepartments').DataTable({
            "ordering": true,
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Tất cả"]],
            "pagingType": "full_numbers",
            "dom": 'Blrtip', // Hides Default Search
            //"dom": 'Bflrtip', // Default Search + Buttons
            "processing": true,
            "serverSide": true,
            "orderMulti": false,

            "ajax": {
                "url": "/Department/getDepartments",
                "type": "POST",
                "datatype": "json"
            },
            "language": {
                "lengthMenu": "Hiển thị _MENU_ bản ghi trong một trang",
                "emptyTable": "Chưa có dữ liệu",
                "info": "Trang thứ _PAGE_ trong tổng số _PAGES_ trang",
                "infoEmpty": "Trống",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Trước",
                    "previous": "Sau"
                },
            },
            //buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5', 'print'],
            buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i>',
                            titleAttr: 'Copy'
                        },
                        {
                            extend: 'excelHtml5',
                            text: '<i class="fa fa-file-excel-o"></i>',
                            titleAttr: 'Xuất ra Excel',
                            title: 'Danh sách Bộ môn',
                            customize: function (xlsx) {
                                var sheet = xlsx.xl.worksheets['sheet1.xml'];

                                //$('row c[r^="C"]', sheet).attr('s', '2');//Bold All rows of a column
                                $('row c[r*="3"]', sheet).attr('s', '25');
                            },
                            exportOptions: {
                                columns: [1, 2, 3]
                            }
                        },
                        {
                            extend: 'csvHtml5',
                            text: '<i class="fa fa-file-text-o"></i>',
                            titleAttr: 'Xuất ra CSV',
                            title: 'Danh sách Bộ môn',
                            exportOptions: {
                                columns: [1, 2, 3]
                            }
                        },
                        {
                            extend: 'pdfHtml5',
                            text: '<i class="fa fa-file-pdf-o"></i>',
                            titleAttr: 'Xuất ra PDF',
                            title: 'Danh sách Bộ môn',
                            exportOptions: {
                                columns: [1, 2, 3]
                            }
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa-print"></i>',
                            titleAttr: 'PRINT',
                            title: 'Danh sách Bộ môn',
                            exportOptions: {
                                columns: [1, 2, 3]
                            }
                        }
            ],
            "fnDrawCallback": function (oSettings) {
                var count = $("#tblDepartments").dataTable().fnSettings().aoData.length;
                if (count != 0) {
                    $(this).find('tbody tr').each(function (index) {
                        $(this).find('td').first(0).text(index + 1);
                    });
                }
            },
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [0] }
            ],
            "aaSorting": [[1, 'asc']],
            "aoColumns": [
                 {
                     "data": null, "autoWidth": false,
                     "sWidth": "100px"
                 },
                {
                    "data": "idDepartment", "autoWidth": false,
                    "sWidth": "200px"
                },
                {
                    "data": "DepartmentName", "autoWidth": true, "mRender": function (data, type, full) {
                        var id = '"' + full['idDepartment'] + '"';
                        var name = full['DepartmentName'];
                        return '<a href=' +
                           '@Url.Action("Details", "Department")/' + full['idDepartment'] +
                           '>' + name + '</a>';
                    }
                },
              {
                  "data": "FacultyName", "autoWidth": false,
                  "sWidth": "200px"
              },
            {
                "data": null,
                "targets": -1,
                "render": function (data, type, full) {
                    // console.log(data,type,full);
                    return "<a  onclick='Edit(" + '"' + full['idDepartment'] + '"' + ")' id='btnEdit" + "`" + full['idDepartment'] + "`" + "' class='btn btn-success btn-xs'>Chỉnh sửa</a>";
                },
                "bSearchable": true,
                "sortable": false,
                "autoWidth": false,
                "sWidth": "50px"
            },
            {
                "data": null,
                "targets": -1,
                "render": function (data, type, full) {
                    // console.log(data,type,full);
                    return " <a onclick='Delete(" + '"' + full['idDepartment'] + '"' + ")' class='btn btn-danger btn-xs'>Xóa</a>";
                },
                "bSearchable": true,
                "sortable": false,
                "autoWidth": false,
                "sWidth": "30px", "visible": RoleCheck
            }
            ]
        });

        //document.onreadystatechange = $('#ddlFacu').change(function () {
        //    //  if ($('#ddlFacu').find('option:selected').text() != "-- Chọn khoa --") {
        //    table.columns(3).search($('#ddlFacu').find('option:selected').text());
        //    //hit search on server
        //    table.draw();
        //    //}
        //    //else {
        //    //    table.columns(3).search($('#ddlFacu').val().trim());
        //    //    table.draw();
        //    //}
        //});

        table.columns().every(function () {
            var that = this;
            $('input', this.footer()).on('keyup change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });
    });
    $('#ddlFacu').change(function () {
        var idcls = $('#ddlFacu').find('option:selected').val()
        $("#facu-id").val(idcls);
        table.columns(3).search($('#ddlFacu').find('option:selected').text());
        //hit search on server
        table.draw();
    });
    $("#btncr").click(function () {
        var productId = $("#facu-id").val();
        var url = '@Url.Action("Create", "Department", new { parameterID = "-1" })';
        url = url.replace("-1", productId);
        $("#MyModalContent").load(url, function () {
            $("#MyModal").modal({
                keyboard: false
            }, 'show');
            bindForm(this);
        });
        return false;
    });
    var Edit = function (idDepartment) {
        $.ajaxSetup({ cache: false });
        var EditUrl = "/Department/Edit/" + idDepartment;
        $("#MyModalContent").load(EditUrl, function () {
            $("#MyModal").modal({
                //backdrop: 'static',
                keyboard: false
            }, 'show');
            bindForm(this);
        });
        return false;
    }

    //#region Delete

    var Delete = function (idDepartment) {
        var Msg = "";
        $.ajax({
            url: "/Department/getDeptDetails",
            type: "GET",
            data: { id: idDepartment },
            success: function (result) {
                // console.log(idFaculty);
                Msg = "Tên bộ môn : <b>" + result[0].DepartmentName + "</b>";


                bootbox.confirm({
                    title: "Xác nhận xóa Bộ môn:",
                    message: Msg,
                    buttons: {
                        confirm: {
                            label: 'Xóa',
                            className: 'btn-success'
                        },
                        cancel: {
                            label: 'Đóng',
                            className: 'btn-danger'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            deleteConfirmed(idDepartment);
                        }
                    }
                });

            },
            error: function (error) {
                console.log(error);
                alert(error)
            }
        });
    }

    var deleteConfirmed = function (idDepartment) {
        $.ajax({
            url: "/Department/deleteConfirmed",
            type: "GET",
            data: { id: idDepartment },
            success: function (result) {

                toastr.success(result + '!');
                table.draw();
            },
            error: function (error) {
                console.log(error);
                alert(error)
            }
        });

    }

    //#endregion Delete

</script>

FaceCheckin/Views/Department/_CreateDepartment.cshtml
@model FaceCheckin.Models.DB.Department
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="MyModalTitle">Thêm mới Bộ môn</h4>
</div>
<style>
    .modal .modal-dialog {
        width: 40%;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "CreateDepartment" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-body">

        <div class="form-horizontal">
            @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
            <div class="form-group cus">
                <label class="control-label">Thuộc khoa</label>
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-sitemap"></i></span>
                    @Html.TextBoxFor(m => m.FacultyName, new { @class = "form-control", @id = "clss", @readonly = true })
                </div>
                @Html.ValidationMessageFor(m => m.FacultyName, "", new { @class = "text-danger" })

            </div>
            @Html.HiddenFor(m => m.idFaculty)

            <div class="form-group cus">
                @Html.LabelFor(m => m.idDepartment, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-list-ol"></i></span>
                    @Html.TextBoxFor(m => m.idDepartment, new { @class = "form-control", @placeholder = "Mã bộ môn" })
                </div>
                @Html.ValidationMessageFor(m => m.idDepartment, "", new { @class = "text-danger" })

            </div>

            <div class="form-group cus">
                @Html.LabelFor(m => m.DepartmentName, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-align-center"></i></span>
                    @Html.TextBoxFor(m => m.DepartmentName, new { @class = "form-control", @placeholder = "Tên bộ môn" })
                </div>
                @Html.ValidationMessageFor(m => m.DepartmentName, "", new { @class = "text-danger" })

            </div>

        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <input type="submit" class="btn btn-primary" value="Thêm mới" id="btnSubmit" />
    </div>
}

<script>
    $(document).ready(function () {
        $.validator.unobtrusive.parse('#CreateDepartment');
        $("#btnSubmit").click(function () {
            if (!$("#CreateDepartment").valid()) {
                return false;
            }
        });
    });
</script>

FaceCheckin/Views/Department/_EditDepartment.cshtml
@model FaceCheckin.Models.ViewModels.DeptVM
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="MyModalTitle">Chỉnh sửa thông tin Bộ môn</h4>
</div>
<style>
    .modal .modal-dialog {
        width: 40%;
    }
   
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "EditDepartment" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">
            @Html.HiddenFor(m => m.Department.idFaculty)
            @*<div class="form-group cus" style="display: none">
                @Html.LabelFor(m => m.Department.idFaculty, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-sitemap"></i></span>
                    @Html.DropDownListFor(m => m.Department.idFaculty, new SelectList(Model.Faculties, "idFaculty", "FacultyName"),
          htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Department.idFaculty, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group cus">
                @Html.LabelFor(m => m.Department.idDepartment, new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-list-ol"></i></span>
                    @Html.TextBoxFor(m => m.Department.idDepartment, new { @class = "form-control", @placeholder = "Mã bộ môn", @readonly = true })
                </div>
                @Html.ValidationMessageFor(m => m.Department.idDepartment)

            </div>
            <div class="form-group cus">
                @Html.LabelFor(m => m.Department.DepartmentName, htmlAttributes: new { @class = "control-label" })
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-align-center"></i></span>
                    @Html.TextBoxFor(m => m.Department.DepartmentName, new { @class = "form-control", @placeholder = "Tên bộ môn" })
                </div>
                @Html.ValidationMessageFor(m => m.Department.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
        <input type="submit" class="btn btn-primary" value="Lưu thay đổi" id="btnSubmit" />
    </div>
}

<script>
    $(document).ready(function () {
        $.validator.unobtrusive.parse('#EditDepartment');
        $("#btnSubmit").click(function () {
            if (!$("#EditDepartment").valid()) {
                return false;
            }
        });
    });
</script>