FaceCheckin/Models/DB/Instructor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceCheckin.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.Courses = new HashSet<Course>();
            this.UserDatas = new HashSet<UserData>();
            this.Classes = new HashSet<Class>();
        }

        [Display(Name = "Mã giảng viên")]
        [RegularExpression("[A-Za-z0-9]*$", ErrorMessage = "Mã giảng viên không chứa ký tự đặc biệt, không sử dụng tiếng việt!")]
        [Required(ErrorMessage = "Mã giảng viên không được để trống!")]
        public string idInstructor { get; set; }
        [Required(ErrorMessage = "Tên giảng viên không được để trống!")]
        [Display(Name = "Tên giảng viên")]
        [RegularExpression("[^.*+?!^${}()@#%=$0-9_]*$", ErrorMessage = "Tên giảng viên không chứa ký tự số và ký tự đặc biệt")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Tên giảng viên phải từ 5 đến 50 ký tự.")]
        //[MinLength(2, ErrorMessage = "Tên giảng viên phải từ 2 đến 50 ký tự.")]
        public string I_Name { get; set; }
        [Required(ErrorMessage = "Email không được để trống!")]
        [EmailAddress(ErrorMessage = "Email chưa đúng định dạng!")]
        [Display(Name = "Email")]
        public string I_Email { get; set; }
        [Required(ErrorMessage = "Số điện thoại không được để trống!")]
        [RegularExpression("[0-9]*$", ErrorMessage = "Số điện thoại chỉ chứa ký tự số!")]
        [StringLength(11, MinimumLength = 10, ErrorMessage = "Số điện thoại phải 10 hoặc 11 số!")]
        [Display(Name = "SĐT")]
        public string I_Phone { get; set; }
        public string I_idDepartment { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<int> I_idAccount { get; set; }

        public virtual Account Account { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<UserData> UserDatas { get; set; }
    }
}

FaceCheckin/Models/ViewModels/InstructorViewModel.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FaceCheckin.Models.ViewModels
{
    public class InstructorViewModel
    {
        public Instructor Instructor { get; set; }
        public IEnumerable<Department> Departments { get; set; }
    }

}

FaceCheckin/Controllers/InstructorController.cs
using FaceCheckin.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using System.Net;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq.Dynamic;
using FaceCheckin.Models.ViewModels;
using FaceCheckin.Security;
using System.Web.Script.Serialization;
using System.Text;

namespace FaceCheckin.Controllers
{
    [CustomAuthorize(Roles = "Admin,Trưởng khoa,Phó khoa,Trưởng bộ môn,Phó bộ môn")]
    public class InstructorController : Controller
    {
        private FCI_DBEntities db = new FCI_DBEntities();

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
        public ActionResult Index()
        {
            var facu = CustomFacu();
            ViewBag.FacuList = facu;
            return View();
        }

        private List<Faculty> CustomFacu()
        {
            var facu = db.Faculties.ToList();
            if (!User.IsInRole("Admin"))
            {
                string tmp = Session["idIns"].ToString();
                facu = (from f in db.Faculties
                        join d in db.Departments on f.idFaculty equals d.idFaculty
                        join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                        where i.idInstructor == tmp
                        select f).ToList();
            }
            return facu;
        }

        [HttpPost]
        public ActionResult getDeptList(string id)
        {
            var lstdept = (from e in db.Departments
                           where e.idFaculty == id.ToString()
                           select new
                           {
                               e.idDepartment,
                               e.DepartmentName
                           }).ToList();
            if (!User.IsInRole("Admin") && !User.IsInRole("Trưởng khoa") && !User.IsInRole("Phó khoa"))
            {
                string tmp = Session["idIns"].ToString();
                var idf = getIdDept(tmp);
                lstdept = (from e in db.Departments
                           where e.idFaculty == id.ToString() && e.idDepartment == idf.ToString()
                           select new
                           {
                               e.idDepartment,
                               e.DepartmentName
                           }).ToList();
            }

            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstdept);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult getInsList(string id)
        {
            var lstins = (from e in db.Instructors
                          where e.I_idDepartment == id.ToString()
                          select new
                          {
                              e.idInstructor,
                              e.I_Name
                          }).ToList();
            JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            string result = javaScriptSerializer.Serialize(lstins);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult getInstructors()
        {
            db.Configuration.LazyLoadingEnabled = false;
            var Draw = Request.Form.GetValues("draw").FirstOrDefault();
            var Start = Request.Form.GetValues("start").FirstOrDefault();
            var Length = Request.Form.GetValues("length").FirstOrDefault();

            var SortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][data]").FirstOrDefault();
            var SortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();

            var idInstructor = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
            var I_Name = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
            var I_Email = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
            var I_Phone = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault();
            var DepartmentName = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();

            int PageSize = Length != null ? Convert.ToInt32(Length) : 0;
            int Skip = Start != null ? Convert.ToInt32(Start) : 0;
            int TotalRecords = 0;
            var insts = (from i in db.Instructors
                         join ab in db.Departments on i.I_idDepartment equals ab.idDepartment
                         select new
                         {
                             idInstructor = i.idInstructor,
                             I_Name = i.I_Name,
                             I_Email = i.I_Email,
                             I_Phone = i.I_Phone,
                             DepartmentName = ab.DepartmentName
                         }).ToList();
            //SEARCHING...
            if (!string.IsNullOrEmpty(idInstructor))
            {
                insts = insts.Where(a => a.idInstructor.Contains(idInstructor)).ToList();
            }
            if (!string.IsNullOrEmpty(I_Name))
            {
                insts = insts.Where(a => a.I_Name.Contains(I_Name)).ToList();
            }
            if (!string.IsNullOrEmpty(DepartmentName))
            {
                insts = insts.Where(a => a.DepartmentName.ToString() == DepartmentName.ToString()).ToList();
            }
            if (!string.IsNullOrEmpty(I_Email))
            {
                insts = insts.Where(a => a.I_Email.Contains(I_Email)).ToList();
            }
            if (!string.IsNullOrEmpty(I_Phone))
            {
                insts = insts.Where(a => a.I_Phone.Contains(I_Phone)).ToList();
            }
            if (!(string.IsNullOrEmpty(SortColumn) && string.IsNullOrEmpty(SortColumnDir)))
            {
                insts = insts.OrderBy(SortColumn + " " + SortColumnDir).ToList();
            }

            TotalRecords = insts.ToList().Count();
            var NewItems = insts.Skip(Skip).Take(PageSize == -1 ? TotalRecords : PageSize).ToList();

            return Json(new { draw = Draw, recordsFiltered = TotalRecords, recordsTotal = TotalRecords, data = NewItems }, JsonRequestBehavior.AllowGet);
        }
        private InstructorViewModel CustomDept()
        {
            var dept = db.Departments.ToList();
            if (!User.IsInRole("Admin"))
            {
                string tmp = Session["idIns"].ToString();
                var idf = getIdDept(tmp);
                dept = (from d in db.Departments
                        join i in db.Instructors on d.idDepartment equals i.I_idDepartment
                        where i.idInstructor == tmp
                        select d).ToList();
                if (!User.IsInRole("Trưởng khoa") && !User.IsInRole("Phó khoa"))
                {
                    dept = (from e in db.Departments
                            where e.idDepartment == idf.ToString()
                            select e).ToList();
                }
            }
            var viewModel = new InstructorViewModel
            {
                Departments = dept
            };
            return viewModel;
        }
        public ActionResult Create(string parameterID)
        {
            var facu = db.Departments.Single(c => c.idDepartment == parameterID).DepartmentName;
            var viewModel = new Instructor
            {
                I_idDepartment = parameterID,
                DepartmentName = facu
            };
            return PartialView("_CreateInstructor", viewModel);
        }

        [HttpPost]
        public ActionResult Create(Instructor instr)
        {
            try
            {
                //var dept = db.Departments.ToList();
                //instr.Departments = dept;
                bool instrExists = db.Instructors.Any(fa => fa.idInstructor.Equals(instr.idInstructor));
                if (instrExists)
                {
                    return new JsonResult
                    {
                        Data = new { ErrorMessage = "Đã tồn tại Giảng viên", Success = false },
                        ContentEncoding = System.Text.Encoding.UTF8,
                        JsonRequestBehavior = JsonRequestBehavior.DenyGet
                    };
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        db.Instructors.Add(instr);
                        db.SaveChanges();
                        return Json(new { success = true, message = "Thêm mới thành công!" });
                    }
                    return PartialView("_CreateInstructor", instr);
                }
            }
            catch (Exception ex)
            {
                return new JsonResult
                {
                    Data = new { ErrorMessage = ex.Message, Success = false },
                    ContentEncoding = System.Text.Encoding.UTF8,
                    JsonRequestBehavior = JsonRequestBehavior.DenyGet
                };

            }
            //  }

        }


        public ActionResult getInsDetails(string id)
        {
            try
            {
                var rslt = (from i in db.Instructors
                            join ab in db.Departments on i.I_idDepartment equals ab.idDepartment
                            where i.idInstructor == id.ToString()
                            select new
                            {
                                idInstructor = i.idInstructor,
                                I_Name = i.I_Name,
                                I_Email = i.I_Email,
                                I_Phone = i.I_Phone,

FaceCheckin/Views/Instructor/Details.cshtml
@model FaceCheckin.Models.DB.Instructor

@{
    ViewBag.Header = "Danh sách các lớp đang đứng hiện tại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<dl class="dl-horizontal">
    <dt style="text-align: left; width: 90px">
        Giảng viên:
    </dt>

    <dd style="margin-left:0px">
        @Html.DisplayFor(model => model.I_Name)
    </dd>

</dl>
<h3>Lớp sinh hoạt</h3>
<div>
    <table class="table table-striped table-hover table-bordered table-responsive">
        <tr>
            <th>
                STT
            </th>
            <th>
                Mã Lớp sinh hoạt
            </th>
            <th>
                Tên Lớp sinh hoạt
            </th>
            <th>
                Thuộc bộ môn
            </th>
            <th>
                Năm học
            </th>
            @foreach (var item in Model.Classes.Select((item, index) => new { item, index }))
            {
            <tr>
                <td>
                    @(item.index + 1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.item.idClass)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.item.ClassName)*@
                    @Html.ActionLink(item.item.ClassName, "Details", "Classes", new { id = item.item.idClass }, null)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.item.Department.DepartmentName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.item.SchoolYear)
                </td>
            </tr>
            }
        </table>
    </div>
    <hr />
    <h3>Lớp tín chỉ</h3>
    <div>
        @*<dl class="dl-horizontal">
                <dt>
                    Giảng viên:
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.I_Name)
                </dd>

            </dl>*@
        <table class="table table-striped">
            <tr>
                <th>
                    STT
                </th>
                <th>
                    Mã Lớp TC
                </th>
                <th>
                    Tên Lớp TC
                </th>
                <th>
                    Ngày bắt đầu
                </th>
                <th>
                    Ngày kết thúc
                </th>
                <th>
                    Năm học
                </th>
                @foreach (var item in Model.Courses.Select((item, index) => new { item, index }))
                {
                <tr>
                    <td>
                        @(item.index + 1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.idCourse)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.item.CourseName)*@
                        @Html.ActionLink(item.item.CourseName, "Details", "Course", new { id = item.item.idCourse }, null)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.EndDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.SchoolYear)
                    </td>
                </tr>
                }
            </table>
        </div>
        <p>
            <button class="buttonPrevious btn btn-primary" style="margin-top: 20px" onclick="goBack()">Trở về</button>
          @*  @Html.ActionLink("Trở về", "Index", null, new { @class = "buttonPrevious btn btn-primary" })*@
        </p>
<script>
    function goBack() {
        window.history.back();
    }
</script>

FaceCheckin/Views/Instructor/Index.cshtml
@model FaceCheckin.Models.ViewModels.InstructorViewModel

@{
    ViewBag.Title = "Quản lý Giảng viên";
    ViewBag.Header = "Danh sách Giảng viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="MyModal" class="modal fade in">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="MyModalContent"></div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="form-group">
    <label class="control-label">Thuộc khoa</label>
    <select id="ddlFacu" class="form-control" style="width:30%" onchange="getDeptList()">
        @foreach (var item in ViewBag.FacuList)
        {
            <text>
                <option value="@item.idFaculty">@item.FacultyName</option>
            </text>
        }

    </select>
</div>
<div class="form-group">
    <label class="control-label">Thuộc bộ môn</label>
    @Html.DropDownListFor(m => m.Instructor.Departments,
       new SelectList(Enumerable.Empty<SelectListItem>(), "idDepartment", "DepartmentName"),
                       new { @class = "form-control", style = "width:30%", @id = "ddlDept" })
    @Html.ValidationMessageFor(m => m.Instructor.Departments, "", new { @class = "text-danger" })
</div>
<input type="hidden" id="project-id" />
@*<p>
    @Html.ActionLink("Thêm mới Giảng viên", "Create", null, null, new { data_modal = "", id = "btnCreate", @class = "btn btn-primary" })
</p>*@
<p>
    <button id="btncr" title="Thêm mới Giảng viên" class="btn btn-primary" style="text-align:right">&nbsp;&nbsp;Thêm mới Giảng viên</button>
    </p>
<div>
    <table id="tblInstructors" style="width:100%" class="table table-striped table-hover table-bordered table-responsive">
        <thead>
            <tr>
                <th>STT</th>
                <th>Mã Giảng viên</th>
                <th>Tên Giảng viên</th>
                <th>Email</th>
                <th>SĐT</th>
                <th>Thuộc bộ môn</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th></th>
                <th id="tht">Mã GV</th>
                <th id="tht">Tên GV</th>
                <th id="tht">Email</th>
                <th id="tht">SĐT</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>
<style>
    /*Buttons to Right Side*/
    div.dt-buttons {
        float: right;
        position: relative;
        margin-left: 10px;
    }
    /*Table Info to right*/
    div.dataTables_wrapper div.dataTables_info {
        float: left;
        padding-top: 8px;
        white-space: nowrap;
    }
</style>
<script>
    var table;
    $(document).ready(function () {
        getDeptList();
        //FillDept();

        $('#tblInstructors tfoot #tht').each(function () {
            var title = $(this).text();
            $(this).html('<input class="FClass form-control" style="width:inherit;" type="text" id="' + title.replace(' ', '_') + '" placeholder="Tìm kiếm theo ' + title + '" />');
        });
        table = $('#tblInstructors').DataTable({
            "ordering": true,
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "Tất cả"]],
            "pagingType": "full_numbers",
            "dom": 'Blrtip', // Hides Default Search
            //"dom": 'Bflrtip', // Default Search + Buttons
            "processing": true,
            "serverSide": true,
            "orderMulti": false,

            "ajax": {
                "url": "/Instructor/getInstructors",
                "type": "POST",
                "datatype": "json"
            },
            "language": {
                "lengthMenu": "Hiển thị _MENU_ bản ghi trong một trang",
                "emptyTable": "Chưa có dữ liệu",
                "info": "Trang thứ _PAGE_ trong tổng số _PAGES_ trang",
                "infoEmpty": "Trống",
                "paginate": {
                    "first": "Đầu tiên",
                    "last": "Cuối cùng",
                    "next": "Trước",
                    "previous": "Sau"
                },
            },
            //buttons: ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5', 'print'],
            buttons: [
                        {
                            extend: 'copyHtml5',
                            text: '<i class="fa fa-files-o"></i>',
                            titleAttr: 'Copy'
                        },
                        {
                            extend: 'excelHtml5',
                            text: '<i class="fa fa-file-excel-o"></i>',
                            titleAttr: 'Xuất ra Excel',
                            title: 'Danh sách Giảng viên',
                            customize: function (xlsx) {
                                var sheet = xlsx.xl.worksheets['sheet1.xml'];

                                //$('row c[r^="C"]', sheet).attr('s', '2');//Bold All rows of a column
                                $('row c[r*="3"]', sheet).attr('s', '25');
                            },
                            exportOptions: {
                                columns: [1, 2, 3, 4, 5]
                            }
                        },
                        {
                            extend: 'csvHtml5',
                            text: '<i class="fa fa-file-text-o"></i>',
                            titleAttr: 'Xuất ra CSV',
                            title: 'Danh sách Giảng viên',
                            exportOptions: {
                                columns: [1, 2, 3, 4, 5]
                            }
                        },
                        {
                            extend: 'pdfHtml5',
                            text: '<i class="fa fa-file-pdf-o"></i>',
                            titleAttr: 'Xuất ra PDF',
                            title: 'Danh sách Giảng viên',
                            exportOptions: {
                                columns: [1, 2, 3, 4, 5]
                            }
                        },
                        {
                            extend: 'print',
                            text: '<i class="fa fa-print"></i>',
                            titleAttr: 'PRINT',
                            title: 'Danh sách Giảng viên',
                            exportOptions: {
                                columns: [1, 2, 3, 4, 5]
                            }
                        }
            ],
            "fnDrawCallback": function (oSettings) {
                var count = $("#tblInstructors").dataTable().fnSettings().aoData.length;
                if (count != 0) {
                    $(this).find('tbody tr').each(function (index) {
                        $(this).find('td').first(0).text(index + 1);
                    });
                }
            },
            "aoColumnDefs": [
                { "bSortable": false, "aTargets": [0] }
            ],
            "aaSorting": [[1, 'asc']],
            "aoColumns": [
                 {
                     "data": null, "autoWidth": true

                 },
                {
                    "data": "idInstructor", "autoWidth": true

                },
                {
                    "data": "I_Name", "autoWidth": true, "mRender": function (data, type, full) {
                        var id = '"' + full['idInstructor'] + '"';
                        var name = full['I_Name'];
                        return '<a href=' +
                           '@Url.Action("Details", "Instructor")/' + full['idInstructor'] +
                           '>' + name + '</a>';
                    }
                },
                  {
                      "data": "I_Email", "autoWidth": true

                  },
                   {
                       "data": "I_Phone", "autoWidth": true

                   }, {
                       "data": "DepartmentName", "autoWidth": true, "visible": false
                   },
                {
                    "data": null,
                    "targets": -1,
                    "render": function (data, type, full) {
                        // console.log(data,type,full);
                        return "<a  onclick='Edit(" + '"' + full['idInstructor'] + '"' + ")' id='btnEdit" + "`" + full['idInstructor'] + "`" + "' class='btn btn-success btn-xs'>Chỉnh sửa</a>";
                    },
                    "bSearchable": true,
                    "sortable": false,
                    "autoWidth": false,
                    "sWidth": "50px"

                },
                {
                    "data": null,
                    "targets": -1,
                    "render": function (data, type, full) {
                        // console.log(data,type,full);
                        return " <a onclick='Delete(" + '"' + full['idInstructor'] + '"' + ")' class='btn btn-danger btn-xs'>Xóa</a>";
                    },
                    "bSearchable": true,
                    "sortable": false,
                    "autoWidth": false,
                    "sWidth": "30px","visible": @(User.IsInRole("Giảng viên") || User.IsInRole("Trợ giảng") || User.IsInRole("Trưởng bộ môn") || User.IsInRole("Phó bộ môn") ? "false" : "true")

                }
            ]
        });


        table.columns().every(function () {
            var that = this;
            $('input', this.footer()).on('keyup change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });
    });
    $('#ddlFacu').change(function () {
        //hit search on server
        table.draw();
    });
    $("#btncr").click(function () {
        var productId = $("#project-id").val();
        var url = '@Url.Action("Create", "Instructor", new { parameterID = "-1" })';
        url = url.replace("-1", productId);
        $("#MyModalContent").load(url, function () {
            $("#MyModal").modal({
                keyboard: false
            }, 'show');
            bindForm(this);
        });
        return false;
    });
    $('#ddlDept').change(function () {
        var idcls = $('#ddlDept').find('option:selected').val()
        $("#project-id").val(idcls);
        table.columns(5).search($('#ddlDept').find('option:selected').text());
        //hit search on server
        table.draw();
    });
    var Edit = function (idInstructor) {
        $.ajaxSetup({ cache: false });
        var EditUrl = "/Instructor/Edit/" + idInstructor;
        $("#MyModalContent").load(EditUrl, function () {
            $("#MyModal").modal({
                //backdrop: 'static',
                keyboard: false
            }, 'show');
            bindForm(this);
        });
        return false;
    }
    function getDeptList() {
        var idFaculty = $("#ddlFacu").val();
        $.ajax
        ({
            url: '/Instructor/getDeptList',
            type: 'POST',
            datatype: 'application/json',
            contentType: 'application/json',
            data: JSON.stringify({
                id: idFaculty
            }),
            success: function (result) {
                $("#ddlDept").html("");
                $.each($.parseJSON(result), function (i, dept) {
                    $("#ddlDept").append($('<option></option>').val(dept.idDepartment).html(dept.DepartmentName))
                })
                var idcls = $('#ddlDept').find('option:selected').val()
                $("#project-id").val(idcls);
                table.columns(5).search($('#ddlDept').find('option:selected').text());
                //hit search on server
                table.draw();
            },
            error: function () {
                alert("Whooaaa! Something went wrong..")
            },
        });
    }
    //#region Delete

    var Delete = function (idInstructor) {
        var Msg = "";
        $.ajax({
            url: "/Instructor/getInsDetails",
            type: "GET",
            data: { id: idInstructor },
            success: function (result) {
                // console.log(idFaculty);
                Msg = "Tên Giảng viên : <b>" + result[0].I_Name + "</b>";


                bootbox.confirm({
                    title: "Xác nhận xóa Giảng viên:",
                    message: Msg,
                    buttons: {
                        confirm: {
                            label: 'Xóa',
                            className: 'btn-success'
                        },
                        cancel: {
                            label: 'Đóng',
                            className: 'btn-danger'
                        }
                    },
                    callback: function (result) {
                        if (result) {
                            deleteConfirmed(idInstructor);
                        }
                    }
                });

            },
            error: function (error) {
                console.log(error);
                alert(error)
            }
        });
    }

    var deleteConfirmed = function (idInstructor) {
        $.ajax({
            url: "/Instructor/deleteConfirmed",
            type: "GET",
            data: { id: idInstructor },
            success: function (result) {

                toastr.success(result + '!');
                table.draw();
            },
            error: function (error) {
                console.log(error);
                alert(error)
            }
        });

    }



</script>